import { type Order } from '../common/types';

export const MOCK_ORDERS: Order[] = [
    {
        id: 'ORD-2026-8801',
        customerName: 'Juan Dela Cruz',
        orderDate: '2026-08-16',
        status: 'Paid',
        items: [
            {
                id: 'item-101',
                productName: 'Handwoven Bayong Bag (Large)',
                image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=300&auto=format&fit=crop&q=80',
                price: 850,
                priceFormatted: '₱850',
                quantity: 1,
            },
            {
                id: 'item-102',
                productName: 'Woven Abaca Placemats (Set of 4)',
                image: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?w=300&auto=format&fit=crop&q=80',
                price: 480,
                priceFormatted: '₱480',
                quantity: 2,
            },
            {
                id: 'item-103',
                productName: 'Handmade Wooden Coasters (Set of 6)',
                image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=300&auto=format&fit=crop&q=80',
                price: 320,
                priceFormatted: '₱320',
                quantity: 1,
            },
        ],
        shippingAddress: {
            fullName: 'Juan Dela Cruz',
            phone: '+63 917 123 4567',
            street: '123 Rizal Street, Brgy. San Antonio',
            city: 'San Pablo City',
            province: 'Laguna',
            postalCode: '4000',
        },
        breakdown: {
            subtotal: 2130,
            shippingFee: 120,
            discount: 150,
            total: 2100,
        },
    },
    {
        id: 'ORD-2026-8802',
        customerName: 'Maria Santos',
        orderDate: '2026-08-17',
        status: 'Paid',
        items: [
            {
                id: 'item-201',
                productName: 'Wireless Noise-Canceling Earbuds',
                image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&auto=format&fit=crop&q=80',
                price: 2499,
                priceFormatted: '₱2,499',
                quantity: 1,
            },
            {
                id: 'item-202',
                productName: 'Ergonomic Matte Mousepad',
                image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format&fit=crop&q=80',
                price: 350,
                priceFormatted: '₱350',
                quantity: 1,
            },
            {
                id: 'item-203',
                productName: 'Braided Type-C Fast Cable (2m)',
                image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=300&auto=format&fit=crop&q=80',
                price: 199,
                priceFormatted: '₱199',
                quantity: 2,
            },
        ],
        shippingAddress: {
            fullName: 'Maria Santos',
            phone: '+63 918 987 6543',
            street: '45 Katipunan Avenue, Brgy. Loyola Heights',
            city: 'Quezon City',
            province: 'Metro Manila',
            postalCode: '1108',
        },
        breakdown: {
            subtotal: 3247,
            shippingFee: 80,
            discount: 200,
            total: 3127,
        },
    },
    {
        id: 'ORD-2026-8803',
        customerName: 'Mark Reyes',
        orderDate: '2026-08-17',
        status: 'To Receive',
        items: [
            {
                id: 'item-301',
                productName: 'Organic Cordillera Whole Bean Coffee (500g)',
                image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300&auto=format&fit=crop&q=80',
                price: 650,
                priceFormatted: '₱650',
                quantity: 2,
            },
            {
                id: 'item-302',
                productName: 'Stainless Steel Pour-Over Dripper',
                image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80',
                price: 890,
                priceFormatted: '₱890',
                quantity: 1,
            },
        ],
        shippingAddress: {
            fullName: 'Mark Reyes',
            phone: '+63 920 555 1212',
            street: '78 Mabini Blvd, Brgy. Central',
            city: 'Calamba City',
            province: 'Laguna',
            postalCode: '4027',
        },
        breakdown: {
            subtotal: 2190,
            shippingFee: 100,
            discount: 0,
            total: 2290,
        },
    },
];