spring.application.name=violetCart-backend

# Datasource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/violet_cart?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.mode=always

# Custom JWT Properties
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
app.jwt.expiration-ms=86400000