import { type Product } from './types';

export const CATEGORIES: string[] = ['All', 'Artisan', 'Home Living', 'Gadgets', 'Beauty'];

export const STORE_PRODUCTS: Product[] = [
    {
        id: 'p1',
        productName: 'Handwoven Bayong Bag',
        imageUrl: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=300&auto=format&fit=crop&q=80',
        seller: "Ana's Artisan Goods",
        price: 850,
        category: 'Artisan',
        rating: 4.9,
        stockQuantity: 15,
        description: 'Eco-friendly handwoven bag made from natural dried pandan leaves. Highly durable, spacious, and crafted by local artisans in Laguna.',
    },
    {
        id: 'p2',
        productName: 'Carved Wooden Stool',
        imageUrl: 'https://images.unsplash.com/photo-1503602642458-232111445657?w=300&auto=format&fit=crop&q=80',
        seller: 'Ocampo Crafts',
        price: 2000,
        category: 'Home Living',
        rating: 4.7,
        stockQuantity: 3,
        description: 'Solid acacia wood stool with a sleek matte finish. Suitable as a side table, plant stand, or minimalist accent seating.',
    },
    {
        id: 'p3',
        productName: 'Minimalist Ceramic Vase',
        imageUrl: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=300&auto=format&fit=crop&q=80',
        seller: 'Flores Home PH',
        price: 500,
        category: 'Home Living',
        rating: 4.8,
        stockQuantity: 0,
        description: 'Matte-finish ceramic flower vase with a Scandinavian silhouette. Waterproof interior, ideal for fresh or dried florals.',
    },
    {
        id: 'p4',
        productName: 'Wireless Mechanical Keyboard',
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
        seller: 'EduTech Gadgets',
        price: 2500,
        category: 'Gadgets',
        rating: 4.9,
        stockQuantity: 22,
        description: 'Compact 75% hot-swappable mechanical keyboard featuring RGB backlighting and dual Bluetooth 5.0 / Type-C connectivity.',
    },
    {
        id: 'p5',
        productName: 'Organic Lip & Cheek Tint',
        imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=300&auto=format&fit=crop&q=80',
        seller: 'Jasmine Organics',
        price: 250,
        category: 'Beauty',
        rating: 4.6,
        stockQuantity: 5,
        description: 'All-natural buildable stain infused with virgin coconut oil and aloe vera extract. Lightweight formula for everyday glow.',
    },
    {
        id: 'p6',
        productName: 'Handcrafted Soy Candle',
        imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=300&auto=format&fit=crop&q=80',
        seller: 'Flores Home PH',
        price: 380,
        category: 'Home Living',
        rating: 4.8,
        stockQuantity: 18,
        description: '100% natural soy wax candle scented with lavender and vanilla essential oils. Hand-poured into a reusable glass jar.',
    },
    {
        id: 'p7',
        productName: 'Ergonomic Desk Mat',
        imageUrl: 'https://images.unsplash.com/photo-1616628188467-8fb29f886bc5?w=300&auto=format&fit=crop&q=80',
        seller: 'EduTech Gadgets',
        price: 650,
        category: 'Gadgets',
        rating: 4.7,
        stockQuantity: 8,
        description: 'Water-resistant vegan leather desk pad with non-slip base. Provides smooth tracking for mice while protecting your desk surface.',
    },
    {
        id: 'p8',
        productName: 'Woven Abaca Placemats (Set of 4)',
        imageUrl: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?w=300&auto=format&fit=crop&q=80',
        seller: "Ana's Artisan Goods",
        price: 480,
        category: 'Artisan',
        rating: 4.9,
        stockQuantity: 2,
        description: 'Heat-resistant woven circular placemats crafted from natural abaca fibers. Adds warmth and texture to dining tables.',
    },
    {
        id: 'p9',
        productName: 'Hydrating Facial Serum',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300&auto=format&fit=crop&q=80',
        seller: 'Jasmine Organics',
        price: 590,
        category: 'Beauty',
        rating: 4.5,
        stockQuantity: 11,
        description: 'Lightweight hyaluronic acid serum formulated with niacinamide and green tea extract for deep moisture and pore care.',
    },
];